version: "3.9"
networks:
  Ecommerce_net:
    driver: bridge
  
volumes:
  mysql_data_vol:
  ecommerce_backend_data_vol:

services:

  mysql_service:
    image: mysql:8.0
    container_name: mysql_Ecommerce
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data_vol:/var/lib/mysql
    networks:
      - Ecommerce_net
    restart: unless-stopped

  ecommerce_backend_service:
    image: sarojdockerworkspace/ecommerce_backend:latest
    container_name: ecommerce_backend_service
    env_file:
      - docker_compose.env
    ports:
      - "8000:8000"
    networks:
      - Ecommerce_net
    depends_on:
      mysql_service:
        condition: service_healthy
      rabbitmq_service:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "
        npm install &&
        cd src &&
        npx sequelize-cli db:create --env development --config config/docker-config.json &&
        npx sequelize-cli db:migrate --env development --config config/docker-config.json &&
        npx sequelize-cli db:seed:all --env development --config config/docker-config.json &&
        cd .. &&
        npm start
      "
  rabbitmq_service:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_server
    networks:
      - Ecommerce_net
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - rabbitmq_server_vol:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment_backend_service:
    container_name: PAYMENT_Service_microservice
    build: ./05_Payment_microservice
    networks:
      - Ecommerce_net
    ports:
      - "3009:3009"
    volumes:
      - ./05_Payment_microservice:/Ecommerce/backend/developer/payment_microservice
      - payment_backend_microservice_vol:/Ecommerce/backend/developer/payment_microservice/node_modules
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=PaymentDB
    depends_on:
      mysql_service:
        condition: service_healthy
      rabbitmq_service:
        condition: service_healthy
    command: >
      sh -c "
        npm install &&
        cd src && 
        npx sequelize-cli db:create --env development &&
        npx sequelize-cli db:migrate --env development &&
        npm start
      "


  api_gateway_service:
    container_name: api_gateway_service_microservice
    build: ./01_ApiGateway
    networks:
      - Ecommerce_net
    ports:
      - "3000:3000"
    volumes:
      - ./01_ApiGateway:/Ecommerce/backend/developer/apigateway
      - apigateway_microservice_vol:/Ecommerce/backend/developer/apigateway/node_modules
  
  remainder_backend_service:
    container_name: Remainder_Service_microservice
    build:
      context: ./03_RemainderMicroService
      dockerfile: Dockerfile
    networks:
      - Ecommerce_net
    ports:
      - "3004:3004"
    volumes:
      - ./03_RemainderMicroService:/Ecommerce/backend/developer/remainder_microservice
      - remainder_microservice_vol:/Ecommerce/backend/developer/remainder_microservice/node_modules
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=RemainderService_db_DEV
    depends_on:
      rabbitmq_service:
        condition: service_healthy
      mysql_service:
        condition: service_healthy
    command: >
      sh -c "
        npm install &&
        cd src &&
        npx sequelize-cli db:create --env development &&
        npx sequelize-cli db:migrate --env development &&
        npm start
      "
  
    
